kivy/buildozer

buildozer/targets/android.py
Should fix this bug:
````
Traceback (most recent call last):
File "/usr/local/bin/buildozer", line 9, in <module>
load_entry_point('buildozer==0.25', 'console_scripts', 'buildozer')()
File "/usr/local/lib/python2.7/dist-packages/buildozer/scripts/client.py", line 13, in main
Buildozer().run_command(sys.argv[1:])
File "/usr/local/lib/python2.7/dist-packages/buildozer/__init__.py", line 967, in run_command
self.target.run_commands(args)
File "/usr/local/lib/python2.7/dist-packages/buildozer/target.py", line 85, in run_commands
func(args)
File "/usr/local/lib/python2.7/dist-packages/buildozer/target.py", line 97, in cmd_debug
self.buildozer.build()
File "/usr/local/lib/python2.7/dist-packages/buildozer/__init__.py", line 194, in build
self.target.build_package()
File …
```
=> ensure whitelist always has a list

buildozer/default.spec, buildozer/targets/android.py, buildozer/targets/ios.py
Allows you to specify custom folders to use when building recipes:
requirements.source.kivy = ../../kivy
This will set `P4A_kivy_DIR` for the Android target and `kivy_DIR` for the iOS target. The iOS portion is completely untested, as I don't have a Mac or an iOS device.
=> allow custom source folders in buildozer.spec

buildozer/targets/android.py
This checks for the last file copied into the dist in p4a. It would be best if p4a actually created a specific file to tell that the dist is complete, but that could break compatibility. It might be best to make p4a do that when Buildozer is updated to support @inclement's Python build script.
=> check for complete dist instead of dist dir

buildozer/__init__.py
Root detection os.geteuid() does not work on win32 environment and
throws AttributeError. Fixed
=> Windows fix

buildozer/__init__.py, buildozer/targets/android.py
@akshayaurora  Here are the changes made:
* android ndk r10 versions are only avalable in ".bin" format.
* Modified the _install_android_ndk function in /buildozer/targets/android.py.
- Checks the version of ndk given in the spec file, whether its greater than 9. 
If it is greater than 9, generate the link containing the .bin url.
* Modified the file_extract function in /buildozer/__init__.py
- Introduced the functionality to handle .bin files.
=> Added support for downloading and handling android ndk r10 versions. Fixes #229 and #227

buildozer/targets/android.py
This should only be merged at exactly the same time that the p4a revamp is changed to the master branch, with the old p4a toolchain kept in a new old_toolchain branch.
It should be followed immediately by releasing a new version of buildozer on pypi.
=> Changed p4a download to pull old_toolchain branch

buildozer/targets/android.py
The issue is that if there is a space in the application path. The application build step fails.
This fix resolves the application path and solves the issue.
=> Fixed Space in app path issue. Fixes #13

buildozer/__init__.py
From the pip changelog:
>pip install --download-cache and pip wheel --download-cache command line flags have been deprecated and the functionality removed. Since pip now automatically configures and uses it's internal HTTP cache which supplants the --download-cache the existing options have been made non functional but will still be accepted until their removal in pip v8.0. For more information please see https://pip.pypa.io/en/stable/reference/pip_install.html#caching
=> Remove pip --download-cache flag (fixes #279)

buildozer/default.spec, buildozer/targets/android.py
This patch adds an option to the spec file that lets you disable automated updates of the android sdk for a given project.
Now you can add `android.skip_updates = True` and the build command will skip the call that decides to download updates to Android SDK components.
I was in the middle of a project when the `buildozer android debug deploy` command decided it wanted to download an update to Android SDK 24 even though I didn't need it, and I didn't want to wait an hour for it to come down. So I added this option to fix that.
Note, I think this is different to issue #267 which wants to disable all possible Internet checks; my patch may fix that but at this point I don't know what other tasks may be referencing the Internet...
=> Add spec option to skip automated update of installed android package

buildozer/targets/ios.py
buildozer fails with
````
Command failed: make ios-deploy
````
This happens because ios-deploy changed their project structure after version 1.7.0. This issue shows again that we should always use releases of other projects instead of the master branch.
=> use ios-deploy version 1.7.0

buildozer/targets/android.py
Fix #284
Currently only fixed target android, because the problem was only seen while building android.
=> Allow app title to contain Unicode characters

buildozer/__init__.py
This cause, that stdout is text file, but `codecs.StreamWriter` encodes string to bytes. #221
=> add python3 compatibility to verbose output for android build (#221)

buildozer/targets/android.py
- `android.py` uses non-existing `critical()` method when `android.p4a_dir` doesn't exist
- interpret tilde (~) for $HOME in `android.p4a_dir`, also makes consistent with `android.ndk_path`, etc.
=> Fix issues with android.p4a_dir spec file property

buildozer/target.py, buildozer/targets/android.py, buildozer/targets/android_new.py
NOTE: requires changes in #323 
Adds adb and p4a commands to buildozer. Arguments must follow `--`, i.e.
`buildozer android_new adb -- devices`
Also provides a handy method of creating an alias to run these commands:
`buildozer android_new adb --alias`
````
To set up ADB in this shell session, execute:
alias adb=$(buildozer android_new adb --alias 2>&1 >/dev/null)
/Users/kived/.buildozer/android/platform/android-sdk-20/platform-tools/adb
````
=> add adb and p4a commands to android/android_new

buildozer/__init__.py, buildozer/default.spec
As per #245 and #30 
Matches files and folders with a list of include patterns similar to exlude_patterns functioning
Priority of include_patterns is above exclude_patterns/exclude_dirs, and below include_exts/exclude_exts
I haven't tested this because I am facing some problems setting up buildozer.
=> Implement source.include_patterns

buildozer/__init__.py
I prefer to keep generated (thus reproducable) things outside of my project folder. Thus, I added this to my `buildozer.spec` file (example):
```
[buildozer]
builddir = /home/jabba/.kivy_builddirs/kivy_project
```
Now, if I launch `buildozer android debug deploy run`, the local folder `.buildozer` is created in this specified builddir instead of the project's folder. However, `bin/` is still created in the project's folder, littering it with a big `.apk` file.
My patch does the following: if builddir is specified (as seen above), then `bin/` (similarly to `.buildozer/`) will be created in the builddir. This way the project folder has the source files and things necessary for the build process are nicely separated.
Rationale: I keep my projects in my Dropbox folder and I like to keep their …
=> put bin/ in builddir if specified in buildozer.spec

buildozer/__init__.py, buildozer/targets/android_new.py
python-for-android already handles this, and the relevant functionality in buildozer isn't working with android_new anyway.
=> let p4a revamp handle pure python requirements

buildozer/default.spec, buildozer/targets/android_new.py
=> allow selection of bootstrap for android_new

buildozer/targets/osx.py
Simple typo. Before builddir resulted in an Errormessage. Now it works.
=> buildozer has no attribute builddir

buildozer/__init__.py
```
(venv) ryan@ryan-mk3:~/g/t/bztest$ buildozer android debug
```
=> throw error early if running in venv

docs/source/installation.rst
Updated the installation info. 
Adding "Android on Ubuntu 15.10  (64bit)" : Tested in my laptop.
Adding `zlib1g:i386` as this package includes debugging symbols for use when debugging applications which use zlib.
I hope everything is correct.
=> update installation info

buildozer/targets/android_new.py
This is essential to work with the argparse handling changes I made recently, as argparse is picky about argument order and won't let the optional arguments come before the subcommand name.
=> Changed p4a command order to work with argparse

buildozer/targets/android_new.py
My previous fix had a mistake; these args must always be passed, not just when calling apk.
=> Always pass required args to p4a in android_new

buildozer/default.spec, buildozer/targets/android_new.py
This both adds the token in default.spec (although not set by default), and uses the appropriate method to handle when it isn't defined.
This needs testing, my buildozer isn't set up to run right now.
=> Added p4a.local_recipes to default.spec and handled its absence

docs/source/installation.rst
openjdk-8-jdk instead of 7 since 7 has "no installation candidate" on Ubuntu16.04.
Other than that it's the same installation commands as Ubuntu15. If i remember correctly this was the only thing i changed from the Ubuntu15 commands, and now my app works normally on androids and is published. 
Just to be sure, i made again a virtual environment with python2.7 and installed everything up to running `buildozer init`. If you want me to test it fully (that is, build a new app and run it on my android to make sure no extra libs are needed) let me know.
=> Update installation.rst (Ubuntu16.04)

buildozer/__init__.py
Found while using buildozer with py3 on old-toolchain as $ buildozer android debug
=> Fix Py3 Incompatable str + bytes issue.

.gitignore, buildozer/default.spec, buildozer/target.py, buildozer/targets/android_new.py
Allow choosing the arch to build for
Usage for arm64:
```
android.arch = arm64-v8a
```
=> android_new: add "android.arch" config option

buildozer/targets/android_new.py
Currently buildozer hardcodes using `python`, but it seems preferable to use whatever Python environment is running buildozer itself. As far as I can tell, `sys.executable` should be a safe way to access this.
=> Made buildozer run p4a using the current sys.executable

buildozer/targets/android.py
In current master. android.skip_updates only skips updating platform-tools and tools, and will still update the build-tools. This is a problem for me at least, because Buildozer will auto update my build tools from 19.1.0, and 19.1.0 is the only version I can get to build correctly.
This is just a quick fix so that it will do no updates with the option enabled
=> android_new: change skip_update to skip all updates

buildozer/default.spec
Most of the Android apps are not fullscreen, statusbar is visible. Default should follow that rule. Only games/navigations are fullscreen by default. This setting makes new users think Kivy is meant only for games, or p4a cant produce app with normal, statusbar visible UI.
=> spec file: dont use fullscreen by default

buildozer/default.spec
99% of apps are portrait oriented, only advanced games are using landscape by default, p4a should follow
=> spec file: use portrait orientation by default

buildozer/__init__.py
Should fix https://github.com/kivy/buildozer/issues/431 , as the deleted code just makes the function return None when presumably an empty list is fine and it should just continue.
Making a PR rather than a straight change in case I'm missing something about what's intended here.
=> Fix file_matches to never return None

README.rst
Thanks to rafalo13 and inclement for suggestions on how to get this to work.  I'm just documenting it for others to use.
=> Adding README.rst entries for how to use buildozer with python3

buildozer/default.spec, buildozer/targets/osx.py
I had trouble using buildozer to package my application on my mac book. As it turned out there where some minor bugs like deprecated URLs and commands not working. I also tried to make it a bit more dynamic, so it works with Python 2.7 and Python 3.X and chooses the corresponding Kivy version to download depending on what Python version you are using.
This commit should fix most of the obvious problems. (I tested it for OS X 10.11.3)
=> trying to fix Kivy install for OS X builds

buildozer/targets/android.py
Using Python 2.7, attempting to run `encode(utf-8)` was throwing `write() argument 1 must be unicode, not str`.
As the file being written has `encoding='utf-8'`, I'm assuming the intention was to decode the lines from an `str` into a unicode string, and I believe that's what this change does.
Please let me know if I've misinterpreted something. Making this change fixed my build locally. Also not sure where I should be targeting this, but it seemed like it might qualify as a hotfix, so I'm targeting master for now.
Also, thank you once again for all the amazing work being done by Kivy! We're porting https://learningequality.org/kolibri/ (the successor platform to KA Lite, our offline version of Khan Academy that I told you about at PyCon 2013) from `python-android` to …
=> Fix unicode coding error in android build target

buildozer/targets/android.py
Fixes the following error using the olds toolchain
...File "/home/kivy/Repos/buildozer/buildozer/targets/android.py", line 857, in _update_libraries_references
if not content[-1].endswith(u'\n'):
IndexError: list index out of range
=> Fix old toolchain index error

buildozer/targets/android_new.py
The buildozer android_new target should allow the webview port to be specified. I tested with flask and it seemed to work.
=> add p4a.port config option; to allow specifiying webview port

buildozer/targets/osx.py
Since the Kivy Downloads section is down due to https://github.com/kivy/kivy/issues/5211 the OSX build target has been failing if you are missing the Kivy dependency. (It's been a couple days since it's been taken down, and troubleshooting this is pretty annoying for any devs who clean their build environment.)
This PR will handle the case when the Kivy dependency cannot be downloaded. It will cover the case where the server returns 404, (such is the case now). It will also cover when a user specifies an incorrect kivy version in osx.kivy_version.
=> Add 404 status code handling on kivy download

buildozer/targets/android.py
Using android_old option exits with error due to an empty "project.properties" file. To solve this problem the next edit should be done:
In recreate the project.properties section, the next line should be changed:
`fd.writelines((line.encode('utf-8') for line in content))` 
-->
`fd.writelines((line.decode('utf-8') for line in content))`
=> Update android.py, updated recreate the project.properties section

buildozer/targets/android_new.py
This argument no longer does anything.
Actually I didn't realise buildozer used it and removed it entirely, causing the build to crash. I've already pushed a fix for that to p4a, but the argument still won't do anything.
=> Removed --sdk argument for p4a

buildozer/__init__.py
When running buildozer using Python 3.5, I get
```
File "/home/richard/Repos/buildozer/buildozer/targets/android.py", line 974, in cmd_logcat
show_output=True)
File "/home/richard/Repos/buildozer/buildozer/__init__.py", line 314, in cmd
stdout.write(chunk.decode('utf-8'))
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xc0 in position 12525: invalid start byte
```
This PR seems to fix it :-)
=> Fix Py3 utf-8 encode error

buildozer/targets/android_new.py
I just saw a p4a issue that assumed the directory `python-for-android-master` was actually the master branch, which it doesn't seem to be. Just changing the directory name seems clear and uncontroversial.
=> Changed p4a directory name for current toolchain

buildozer/default.spec, buildozer/targets/android.py
This depends on kivy/python-for-android#1213.
This feature will allow users to add their own activities to the manifest file. It can be used to start Java activities using pyjnius. See kivy/python-for-android#1213 for more information.
=> Allow adding Java activities to the manifest

buildozer/default.spec, buildozer/targets/android.py
As in title, this allows setting the [activity launch mode](https://developer.android.com/guide/topics/manifest/activity-element.html#lmode) in the AndroidManifest from buildozer.spec.
It is cumbersome to manually (or via custom scripts) modify the manifest at `[app project]/.buildozer/android/platform/python-for-android/dist/[app]/templates/AndroidManifest.tmpl.xml`.
related: https://github.com/kivy/python-for-android/pull/1256
=> allow setting launchMode for the main activity in the manifest

Dockerfile, README.rst
Buildozer Dockerfile, fixes #589
Installs buildozer and dependencies, documents usage.
To build the image you first need to `cd` to where the `Dockerfile` is,
then run:
```sh
docker build --tag=buildozer .
```
Then you can use the container e.g. with:
```sh
docker run --volume "$(pwd)":/home/user/hostcwd buildozer --help
```
The above command mounts host current working directory in container using `--volume` option.
Also added workaround for #625
=> buildozer Dockerfile, fixes #589

buildozer/tools/packer/scripts/additional-packages.sh
The reason for forcing such an old version isn't valid any longer anyway.
=> Remove obsolete sh package dependency

buildozer/targets/android.py
Prevents build step from failing.
Taken from https://github.com/kivy/buildozer/pull/691 (@gautam-kumar-22) to help push it along since it seems stuck.
Fixes #312, #597, #599, #603, #606, #613, #632, #636, #647, #649, #662
=> Changes how is_gradle_build is detected.

buildozer/libs/version.py
Fixes an issue where prerelease versions were parsed correctly, but not converted to a string correctly.
For example:
Build tools version "28.0.0-rc1" was parsed as "28.0.0rc1", resulting in the following error:
```bash
```
This might be a poor fix, and could cause issues elsewhere, so I'm happy to make any necessary changes.
=> fix prerelease version

README.rst
Refactors Python 2/3 install instructions.
Makes explicit difference between host and target Python.
Both host Python versions are supported seamlessly while target Python
requires different actions depending on the version.
=> Updates Python 3 install instructions, fixes #710

buildozer/targets/android.py
If this file doesn't exist then there's probably no point attempting to continue, as buildozer's assumptions are automatically all messed up.
Also should not use `except Exception:`! I think this probably obscured an error someone reported on discord.
=> Improved error handling if p4a setup.py can't be read

buildozer/targets/android.py
This fixes:
```
$ buildozer android debug
Traceback (most recent call last):
File "/usr/local/bin/buildozer", line 11, in <module>
load_entry_point('buildozer==0.36.dev0', 'console_scripts', 'buildozer')()
File "/usr/local/lib/python3.6/dist-packages/buildozer/scripts/client.py", line 13, in main
Buildozer().run_command(sys.argv[1:])
File "/usr/local/lib/python3.6/dist-packages/buildozer/__init__.py", line 1059, in run_command
self.target.run_commands(args)
File "/usr/local/lib/python3.6/dist-packages/buildozer/target.py", line 92, in run_commands
func(args)
File "/usr/local/lib/python3.6/dist-packages/buildozer/target.py", line 102, in cmd_debug
self.buildozer.prepare_for_build()
File "/usr/local/lib/python3.6/dist-packages/buildozer/__init__.py", line 176, in prepare_for_build …
```
=> Allow for `install_reqs` line having whitespace at start.

buildozer/default.spec, buildozer/targets/android_new.py
This will let us specify the NDK API, which will allow us to create an .apk that has a min API of 19 (or lower?) while still allowing the targeting of higher API levels, like 27. 
Adds a new entry to the buildozer spec as well.  Resolves #758
=> allow specifying of Android NDK API. Resolves #758

Dockerfile, setup.py
it's nice to build docker with current, bleeding edge or even uncommited version of buildozer, instead of using only stable, pypi pushed buildozer version. 
In such case, --build-arg git=true should be used.
=> Docker from current git

buildozer/__init__.py, buildozer/targets/android.py
buildozer failed with downloading recent versions of android NDK.
This diff reflects the changes in the android NDK download urls.
I tested it with the recent NDKs (16b,17c).
=> fix ndk URLs

buildozer/__init__.py
Other wise you get a UnicodeEncodeError in python3.
=> Handle buildozer.spec with unicode chars

buildozer/__init__.py
Fix python 2 crash when reading config file, also see https://github.com/kivy/buildozer/commit/c66af5dc0bf7420df6d71c26bee55f085b80c93b#commitcomment-31965387
=> Fix python 2 crash when reading config file

buildozer/default.spec, buildozer/targets/android.py, buildozer/targets/android_new.py
With these changes, buildozer defaults to using python-for-android's master branch, and with the next defaults will compile successfully.
=> Update for p4a master

buildozer/targets/android_new.py
Fixes https://github.com/kivy/buildozer/issues/798
=> Removed redundant --ndk-api argument and fixed default value

buildozer/default.spec, buildozer/target.py, buildozer/targets/ios.py
Currently (for an iOS build) buildozer downloads 2 platform build dependencies from github repos:
* kivy-ios
* ios-deploy
This change allows the repo/branch of those dependencies to be specified in `buildozer.spec`, either as local (custom) checkouts, or by specifying a git URL and branch. In fact, it allows any git-based dependency to be handled in the same manner, either by specifying a local checkout directory to use, or by specifying a URL/branch pair.
This has been essential for me in order to lock the versions of upstream dependencies during periods of high code churn (or to refer my build to forked, bug-fixed repos of these upstream dependencies)
`buildozer.spec` can now be used to specify the location of these repos as follows:
```
ios.kivy_ios_url = …
```
=> Specify GitHub branches in buildozer.spec

buildozer/targets/ios.py
This makes use of the newly added `--add-frameworks` flag in kivy-ios to add frameworks named in
`ios.frameworks` in `buildozer.spec`
Note, this is a WIP until https://github.com/kivy/kivy-ios/pull/342 is accepted (which this change relies on).
This would fix https://github.com/kivy/buildozer/issues/790
=> Support the --add-frameworks flag in kivy-ios

docs/source/installation.rst
`cython==0.28.6` seems to be doing just fine on p4a until now.
https://github.com/kivy/python-for-android/blob/df60061/Dockerfile#L120
=> Update cython version from the docs

README.md
Removed confusing references to Python 2 use.
Fixes https://github.com/kivy/buildozer/issues/774 (along with some kivy doc changes I'm pushing).
=> Updated README for Python 3

buildozer/targets/android.py
Uses `yes` command and `sdkmanager --licenses` flag to automatically accept licenses.
This is a more robust, straight forward and more conventional way of accepting licenses automatically.
Plus it makes it possible to auto accept license even with low level of verbosity (`log_level = 1`).
=> refactor auto accept license

buildozer/__init__.py
When some command fails, it's good to know what envs was set, to be able to reproduce error. 
Also few formatting changes forced by flake8
=> Show envs when run2

buildozer/__init__.py
=> Add ci_mode to toggle download progress

buildozer/__init__.py
I don't think the list of all files that unzip has extracted is really of any use.
At least for the NDK the amount of stuff it logs is huge.
=> feat: make unzip quiet

buildozer/default.spec
x86_64 was missing from the choices in the spec file.
=> add missing android arch to spec file

Dockerfile
Makes it possible to build Android APKs directly from Docker.
Tested by building sucessfully both:
* kivy-garden/garden.zbarcam (20190303)
* AndreMiras/EtherollApp (20190217)
After building the image with:
```
docker build --tag=kivy/buildozer .
```
The following command was used to build the Android APK:
```
docker run \
--volume "$HOME/.buildozer":/home/user/.buildozer \
--volume "$(pwd)":/home/user/hostcwd \
kivy/buildozer android debug
```
Note the system dependencies were also sorted alphabetical to ease maintenance.
Later more dependencies can be added if needed to build a given recipe.
=> Updates system requirements needed to build recipes

Dockerfile, buildozer/__init__.py, tests/test_buildozer.py
Running `buildozer unknown_command` should show a meaningful error and exit. Fixes regression introduced in 4936d31 and adds unit tests.
Also updates other tests `assert` keyword rather than `self.assert*` in order to keep style consistent.
Last, minor `Dockerfile` documentation update as per recent @tshirtman feedback.
=> Handles unknown command/target error gracefully, closes #812

buildozer/__init__.py
Hi.
I spend 2 days to detect problem with debugging program on my Xiaomi device. So I propose this simple patch which allow replace character which cannot be decode to UTF-8.
Best regards.
Draqun
=> Fix for bug when logcat value which cannot be decode to utf-8

buildozer/targets/android.py
Guessing based on this logoutput
```
[INFO]:    # Copying APK to current directory
[INFO]:    # APK filename not found in build output. Guessing...
[INFO]:    # Found APK file: /home/data/.buildozer/android/platform/build/dists/zeronet/build/outputs/apk/release/zeronet-release-unsigned.apk
[INFO]:    # Add version number to APK
[INFO]:    # APK renamed to zeronet-0.6.5.1-release-unsigned.apk
[DEBUG]:   -> running cp /home/data/.buildozer/android/platform/build/dists/zeronet/build/outputs/apk/release/zeronet-release-unsigned.apk zeronet-0.6.5.1-release-unsigned.apk
...
IOError: [Errno 2] No such file or directory: u'/home/data/.buildozer/android/platform/build/dists/zeronet/build/outputs/apk/release-unsigned/zeronet-release-unsigned.apk'
```
=> fix: drop release-unsigned from release output path

buildozer/__init__.py
Don't print all environment variables for every single cmd() call, refs:
https://github.com/kivy/buildozer/pull/802/files#r261844323
Leaves only one `log_env()` call on command failed.
=> Removes extra log_env() call

buildozer/default.spec, buildozer/targets/android.py
Support for feature added in https://github.com/kivy/python-for-android/pull/1684
=> Support p4a uses-library argument

buildozer/targets/android.py, tests/test_buildozer.py
ANT installation path was hardcoded so if you changed the installation path, it will download every time you run `buildozer android XXX`
```
```
I am sorry, I did not found any easy way to test this change since it will download ANT which we don't want that on testing
=> Download Apache ANT at the same path as the buildozer.spec android.ant_path option

buildozer/__init__.py
Flushing on every output line seems to guarantee that the 'Accept [y/N]' line is printed. As far as I can see there's no reason not to do this.
This fixes the issue where the license text is shown, but then buildozer hangs without actually showing the line asking the user to press `y`.
=> Made sure to print all lines of license question by always flushing

buildozer/targets/android.py
buildozer had a glitch when building for 'service_only' bootstrap: it generated --window and --orientation parameters for the apk command which are not supported by the service_only bootstrap.
Together with kivy/python-for-android#1725 service_only can now be built with buildozer.
=> disable orientation and window option for service_only bootstrap

buildozer/default.spec, buildozer/targets/android.py
This PR extends the android.add_libs to arm64-v8a .
=> Extend add_libs to arm64-v8a

buildozer/default.spec, buildozer/targets/android.py
This PR adds the ability to use any p4a fork. So combined with buildozer.spec file key `p4a.branch` it will allows us to test any pull requests of `kivy/python-for-android` using buildozer. Also, an user could use his own fork/branch of p4a editing two keys from his buildozer.spec file: `p4a.fork` and `p4a.branch` to make use of his own fork/branch of p4a.
So...in this PR we do:
- add a new key to buildozer.spec file: `p4a.fork`
- check on each build that fork/branch has not been changed, and if so, remove the old p4a installation (which will trigger a new p4a's installation)
- move key `p4a.branch` to proper section (python-for-android)...of course this is not mandatory, it's only to be neatest and to make easier to find the key
- fix a pep8 error (two blank lines before class)
**Note:** …
=> New feature: allow to use a p4a fork

buildozer/targets/android.py, tests/test_buildozer.py
So this way, if an user has not specified the android's NDK version via buildozer.spec's file, We will try to get the recommended one by p4a, established in `pythonforandroid.recommendations.py` file, so depending on the version of p4a used, we can use an android NDK or another.
This will allow us to solve the problem where p4a needs to move to a newer android NDK in develop branch, but also we need to preserve the old one for p4a's master branch (like the `ndk-r19-migration` thing that we are dealing this days in p4a, kivy/python-for-android#1722).
**Note:** in case that an old version of p4a is used, previous to 2019, where the p4a's recommendations file still not existed, We will fallback to buildozer's hardcoded NDK version
=> Add ability to get p4a's recommended android's NDK version

buildozer/targets/android.py
This prevent using the same build (armv7a) when building another arch using profile (arm64-v8a)
Note: my asumption is that because buildozer pass the storage-dir, p4a assume it is already separated per arch, therefore reuse the same build even if the arch is different. Which is not supposed to happen right?
If this is not supposed to happen, and a fix is applied to p4a, this merge is unecessary.
=> Separate build per android.arch

buildozer/targets/android.py
If i do 2 build with the same buildozer spec, but 2 profiles with different arch (or 2 buildozer spec), i don't want the final apk to be overwritten. So now the final apk name contains the arch:
For example:
- `connectage-0.4.0.23-arm64-v8a-release.apk`
- `connectage-0.4.0.23-armeabi-v7a-release.apk`
=> Rename final apk with arch in the name

buildozer/targets/android.py
=> fix: show output of sdk update if auto_accept_license is false

buildozer/targets/android.py
This PR fixes packaging for current `p4a` `develop` branch.
Needed due to changes in `p4a` PR https://github.com/kivy/python-for-android/pull/1986.
=> Fixes packaging for current p4a develop branch

buildozer/__init__.py, buildozer/targets/android.py, buildozer/targets/osx.py, tests/scripts/test_client.py, tests/test_buildozer.py
Made a few improvements while checking NDK version downloads were working correctly.
I'm pretty satisfied that everything is good, thanks @opacam for doing the real work here.
In particular, the scenarios that need covering are:
- New install: buildozer downloads p4a latest release then a matching NDK.
- P4a already downloaded: buildozer checks the p4a recommendations and fetches a matching NDK.
- NDK already downloaded: buildozer downloads p4a latest release, then fetches a matching NDK if necessary.
I was worried there might be some issues with how buildozer stores the NDKs, but it all seems basically good.
Also added a new command `buildozer appclean` that deletes the build directory (i.e. app_dir/.buildozer), because this is much nicer than telling users to delete it themselves.
=> Code improvements around NDK download

tests/test_buildozer.py, tox.ini
Mocking `for line in open()` should be done via `StringIO`.
Also uses `pytest` in `tox.ini` so assert errors are more verbose.
=> Fixes test_p4a_recommended_android_ndk_found() mocking

buildozer/targets/android.py
When multiple `android.add_libs_*` are present, buildozer is trying (and failing) to copy libs also for non-current arch.
This PR goal is to leave the `buildozer.spec` file unchanged when targeting multiple archs except for the `android.arch` option.
=> Add libs only for current arch

buildozer/__init__.py
The paths tested against `source.exclude_dirs` (set in buildozer.spec) are cast to lowercase but the paths in source.exclude_dirs are left as-is:
https://github.com/kivy/buildozer/blob/182d13f1027d4c16e04e1096c94ed3e488226330/buildozer/__init__.py#L775
https://github.com/kivy/buildozer/blob/182d13f1027d4c16e04e1096c94ed3e488226330/buildozer/__init__.py#L784
This could result in confusion if the user lists non-lowercase paths in source.exclude_dirs as they would never match anything.
=> spec file: cast paths in source.exclude_dirs to lowercase

buildozer/default.spec, buildozer/targets/android.py
This PR introduces a set of options which deal with integration of java/kotlin libraries
- android entrypoint: this option already existed in buildozer but was not implemented in p4a.
this allows to specify a custom class inherited class from org.kivy.android.PythonActivity as entrypoint
- android apptheme: specifies a custom app-theme for the main activity, will be generated into the manifest
- add_compiler_options
- gradle-repository: with this option it is possible to specify additional repositories for the gradle build
- packaging-options: results in packagingOptions in the gradle script, can be necessary to resolve conflicts in java/kotlin packages
this PR also includes changes from #912
this PR also needs kivy/python-for-android#1869
=> customizability options

README.rst
Clarify that a config token must exist in the spec file before they can be overridden by an environment variable.
=> clarify overriding of config tokens

buildozer/targets/android.py
When I use p4a (https://github.com/kivy/python-for-android/commit/b1f6064d9644a532f52728218e42da37d54f502c) and buildozer (e5cc1855da9757c0f99449bddbc2aebdce450e58) to build an android apk with gradle, the apk gets named as e.g.:
`Electrum__arm64-v8a-4.0.0.0-arm64-v8a-debug.apk`
Note that the arch is duplicated...
See these commits, which collectively ultimately lead to the broken naming:
https://github.com/kivy/buildozer/commit/c92b3ef9253e60f8a622844a045f4689b9296d1e
https://github.com/kivy/buildozer/commit/d483847bb57fb46d4d5b1e4b5ca8bca4a41c08a9
https://github.com/kivy/buildozer/commit/9fcf28ba447d0d4930f98d515daad2b290d20aa7
=> android gradle build: fix apk name

buildozer/default.spec
Note that this is only the template spec file and
`DEFAULT_ANDROID_NDK_VERSION` fallback is left untouched.
=> Updates default buildozer.spec NDK from 17c to 19b

Dockerfile
Original Issue is: [ImportError: cannot import name 'main' #1052](https://github.com/kivy/buildozer/issues/1052)
This is the fix I show on [this post](https://github.com/kivy/buildozer/issues/1052#issuecomment-611006248)
=> [Python3] #1052 ImportError: cannot import name 'main'

.github/workflows/test_python.yml, README.md, tox.ini
Also enables report to coveralls.io via GitHub Action.
Note the `COVERALLS_REPO_TOKEN` was setup via:
https://github.com/kivy/buildozer/settings/secrets
And is accessible for repos admin via:
https://coveralls.io/github/kivy/buildozer
This is a follow up for https://github.com/kivy/buildozer/pull/1059 branching from upstream to have access to the secrets
=> Setup coverage testing, closes #1058

tests/targets/test_android.py
This is a best effort approach trying to increase the coverage of that module. Therefore some tests are not completely isolating all dependencies via `mock.patch`-ing.
Subsequent pull request could cover more methods and focus on edge case.
This increases the overall coverage from 20% to 25% and `buildozer/targets/android.py` coverage from 15% to `24%`.
=> Starts unit testing buildozer/targets/android.py

buildozer/__init__.py, buildozer/jsonstore.py, buildozer/targets/android.py, buildozer/targets/osx.py, tox.ini
* Organises linter errors and check tests/ directory
* PEP8 fixes
- E129 visually indented line with same indent as next logical line
- E226 missing whitespace around arithmetic operator
- E241 multiple spaces after ','
- E262 inline comment should start with '# '
- E301 expected 1 blank line, found 0
- E303 too many blank lines
- E502 the backslash is redundant between bracket
- E741 ambiguous variable name
- W391 blank line at end of file
=> Linting organisation and fixes

.github/workflows/test_python.yml
~~This is some tests and not supposed to be merged until completed~~ Completed!
Coveralls.io now runs on pull requests as well.
The report is automatically uploaded on coveralls.io however it needs to be accessed by copying the report URL to review it.
Next up would be to have it commenting on the pull request to see on first sight if it increased or decreased.
Also made a couple of adjustment to the workflow file to clarify between requirements building, Docker build/run and actual testing.
=> Fixes coveralls.io on pull requests

.github/workflows/test_python.yml
Creates a dedicated job for Docker testing so it can run in parallel with the other tests.
Prior this change the CI was running in 3 minutes, it now runs in 2.
=> Dedicated Docker build/run job

tests/targets/test_android.py
Increases android.py coverage from 24% to 36% and total coverage from 25% to 29%.
Note that this tests would have caught the glob issue reported in #1044.
=> Unit tests TargetAndroid.build_package()

.github/workflows/test_python.yml, tests/targets/test_android.py
Increases coverage from 28% to 30%.
=> Also tests against macOS platform

.github/workflows/test_python.yml
Checks:
- buildozer installs
- buildozer --help
- buildozer init
Currently `buildozer android debug` is not ran as it's not yet fully reliable.
=> Integration testing

.github/workflows/test_python.yml
calling the `p4a` command would trigger all the downloads so we can verify it works as expected. Note this phase adds a 1.5 minute overhead
=> Checks SDK, NDK and p4a get downloaded on first run

Dockerfile
This is required for the minimal build, closes #1096
Also drops Python 2 dependency.
Integration test will come after #1093 is merged
=> :bug: Fixes missing libssl-dev dependency

.github/workflows/test_python.yml, CHANGELOG.md
Also fixes CHANGELOG.md descending PR order
=> :rotating_light: Build integration test

.github/workflows/pypi-release.yml, setup.py
New `pypi-release.yml` workflow for deploying to PyPI.
The scoped token is already setup in:
https://github.com/kivy/buildozer/settings/secrets
Also fixes `setup.py` classifier. The error was:
HTTPError: 400 Client Error: Invalid value for classifiers.
Error: Classifier 'Programming Language :: Python :: 3.6Programming Language :: Python :: 3.7Programming Language :: Python :: 3.8'
is not a valid classifier. for url: https://upload.pypi.org/legacy/
Tested by changing the version to an existing one and testing the upload:
```
Uploading distributions to https://upload.pypi.org/legacy/
Uploading buildozer-1.0-py3-none-any.whl
Uploading buildozer-1.0.tar.gz
HTTPError: 400 Client Error: File already exists.
See https://pypi.org/help/#file-name-reuse for url: https://upload.pypi.org/legacy/
``` …
=> :green_heart: Automatically publish to PyPI upon tagging

Dockerfile
Applies "cache busting" to avoid apt cache miss:
https://docs.docker.com/develop/develop-images/dockerfile_best-practices/#run
The error was:
```
After this operation, 905 MB of additional disk space will be used.
E: Failed to fetch http://security.ubuntu.com/ubuntu/pool/main/f/file/libmagic-mgc_5.32-2ubuntu0.3_amd64.deb 404 Not Found [IP: 91.189.88.142 80]
E: Failed to fetch http://security.ubuntu.com/ubuntu/pool/main/f/file/libmagic1_5.32-2ubuntu0.3_amd64.deb 404 Not Found [IP: 91.189.88.142 80]
E: Failed to fetch http://security.ubuntu.com/ubuntu/pool/main/f/file/file_5.32-2ubuntu0.3_amd64.deb 404 Not Found [IP: 91.189.88.142 80]
E: Failed to fetch http://security.ubuntu.com/ubuntu/pool/main/l/linux/linux-libc-dev_4.15.0-96.97_amd64.deb 404 Not Found [IP: 91.189.88.142 80]
E: Failed to …
```
=> :whale: Fixes Docker apt cache missed

README.md, buildozer/__init__.py, buildozer/jsonstore.py, buildozer/libs/_structures.py, buildozer/libs/version.py, buildozer/target.py, buildozer/targets/android.py, buildozer/targets/ios.py, buildozer/targets/osx.py, tests/scripts/test_client.py, tests/targets/test_android.py, tests/test_buildozer.py, tox.ini
- Drops Python 2 imports
- Drops `if IS_PY3` constructions
- Drops `object` inheritance
- Drops `__future__` imports
- Drops `mocks` dependency
- Uses Python 3 `super()`
=> :wastebasket: Removes Python 2 constructions

.github/workflows/test_python.yml, README.md, buildozer/__init__.py, buildozer/jsonstore.py, buildozer/libs/_structures.py, buildozer/libs/version.py, buildozer/scripts/client.py, buildozer/scripts/remote.py, buildozer/target.py, buildozer/targets/android.py, buildozer/targets/ios.py, buildozer/targets/osx.py, tests/targets/test_android.py, tox.ini
Linter fixes:
- E123 closing bracket does not match indentation of opening bracket's line
- E125 continuation line with same indent as next logical line
- E231 missing whitespace after ','
- E265 block comment should start with '# '
- E302 expected 2 blank lines, found 1
- E305 expected 2 blank lines after class or function definition, found 1
- E731 do not assign a lambda expression, use a def
- F401 imported but unused
- F821 undefined name
- W605 invalid escape sequence
Also removes a Python 2 reference from the README.md
=> :wastebasket: Linter fixes and README.md update

buildozer/default.spec, buildozer/targets/android.py
This flag is available in p4a and can be useful to have buildozer side too.
Also refs #1079
=> :sparkles: Adds p4a --numeric-version support

tests/targets/test_android.py
Refactored the tests for `TargetAndroid`, as requested in #1119.
=> TargetAndroid tests

tests/targets/test_android.py
=> :white_check_mark: Tests android.numeric_version config

.github/workflows/test_python.yml, docs/source/installation.rst
Note the `sed` expression got updated to work for both OS.
Also workaround openssl lib install on macOS, the error was:
```
RAN: /bin/bash -c 'venv/bin/pip install Cython'
STDOUT:
WARNING: pip is configured with locations that require TLS/SSL, however the ssl module in Python is not available.
Collecting Cython
WARNING: Retrying (Retry(total=4, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError("Can't connect to HTTPS URL because the SSL module is not available.")': /simple/cython/
WARNING: Retrying (Retry(total=3, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError("Can't connect to HTTPS URL because the SSL module is not available.")': /simple/cython/
WARNING: Retrying (Retry(total=2, connect=None, read=None, …
```
=> :white_check_mark: Also integration test on macOS

buildozer/targets/android.py, tests/targets/test_android.py
The SDK Tools package is deprecated and no longer receiving updates:
https://developer.android.com/studio/releases/sdk-tools
Also drops the "tools" package install as it's considered obsolete.
Migrates to command line tools:
https://developer.android.com/studio#cmdline-tools
https://developer.android.com/studio/command-line
Makes it possible to use both OpenJDK 8 and more recent versions.
Tested successfully in Arch with OpenJDK 10.
=> :arrow_up: Migrates to Command line tools

setup.py
According to @AndreMiras ([ref](https://discord.com/channels/423249981340778496/490493814281338890/719947159570612264)), buildozer should be considered to be stable.
This edit lets PyPI know.
(This feels like it deserves a little fanfare: 🥳🎉 Congrats and thanks to you all for your work!)
=> Declare Buildozer to be Stable

buildozer/__init__.py, buildozer/default.spec, docs/source/specifications.rst
Garden are now installed like normal packages, refs:
https://kivy.org/doc/stable/api-kivy.garden.html#update-to-garden-structure
=> :fire: Drops garden support

buildozer/__init__.py, buildozer/scripts/remote.py
SafeConfigParser was renamed to ConfigParser in Python 3.2. Use of it in Python 3.7 gives a DeprecationWarning.
As Buildozer is not supported at below Python 3.2, simply replaced all mentions.
Warning is no longer issued.
=> SafeConfigParser deprecated.

.github/workflows/android.yml, .github/workflows/ios.yml, README.md, buildozer/default.spec, buildozer/targets/ios.py
Updates & fixes support for iOS target, covers the following:
- Build integration test
- Updates to new kivy-ios structure
- Bumps to ios-deploy 1.10.0 (`make` replaced by `xcodebuild`)
- Makes it possible to toggle code signing (now disabled by default)
Note this is the first iteration of a longer serie.
Subsequent pull requests will try to improve the following:
- code signing process (toggle not fully integrated)
- actual deployment (not yet tested)
- unit tests (mainly `buildozer/targets/ios.py`)
- other forms of technical debt
=> :green_apple: Improves iOS support

buildozer/targets/ios.py, tests/targets/test_android.py, tests/targets/test_ios.py, tests/targets/utils.py
- basic ios target test
- refactors existing android test for code sharing
- changes `call_build_package()` to simple function
Grows `buildozer/targets/ios.py` coverage from 11% to 24%.
This setups the canvas for more tests to come later.
=> :white_check_mark: Unit test ios target

buildozer/targets/ios.py, tests/targets/test_android.py, tests/targets/test_ios.py, tests/targets/utils.py
This is a follow-up for #1160 and #1168.
Addresses the following:
- grows `buildozer/targets/ios.py` target coverage from 24% to 56%
- fixes `AttributeError` on `TargetIos` error call
Next up should be improving:
- code signing process (toggle off not fully integrated)
- actual deployment (not yet tested)
- further increase `buildozer/targets/ios.py` test coverage
=> :white_check_mark: Increases ios target test coverage

docs/source/installation.rst
Noticed the "Targeting iOS" heading was subordinate to "Targeting Android". This simple change promotes the iOS heading to the same level as Android.
=> Fixes heading for iOS target

buildozer/default.spec, buildozer/targets/android.py
allow using Lottie animation as splashscreen on Android
=> Add support for --presplash-lottie option of p4a

buildozer/default.spec, buildozer/targets/android.py, tests/targets/test_android.py
Just added support for allow_backup inside buildozer.spec (issue #881)
=> Fix issue #881: Add android.allow_backup parameter to buildozer.spec

buildozer/default.spec, buildozer/targets/android.py, tests/targets/test_android.py
as per #1224 
1. We need to pass the option explicitly to keep old default behaviour in the future
2. user should be able to control whether distutils support is enabled or not.
=> Add option for controlling p4a distutils support, fixes #1224

buildozer/default.spec, buildozer/targets/android.py, tests/targets/test_android.py
Added support for https://github.com/kivy/python-for-android/pull/2208
(I'm not sure about using `join(self.buildozer.root_dir, backup_rules)` though)
=> Add android.backup_rules parameter to buildozer.spec

buildozer/targets/android.py
The current workaround for WSL doesn't work with WSL 2 because WSL 2 has changed the format of the uname.
Examples:
For WSL 1:
uname()[2] = '4.4.0-18362-Microsoft'
For WSL 2:
uname()[2] = '4.19.104-microsoft-standard'
=> WSL workaround now accommodates WSL 2

buildozer/__init__.py
It was not at all obvious to me that e.g. `source.exclude_patterns = Makefile,*.png` would not work because the pattern is matched - case-sensitively (on Linux at least) - against a lowercase version of the file's path. This seems like a better solution than simply documenting that the pattern must be lowercase.
=> make include_exts etc. properly case-insentitive

README.md
I made GitHub action to build packages for Android with Buildozer. You can find it [here](https://github.com/ArtemSBulgakov/buildozer-action).
I want to add a link to the Readme because many people don't know that there is such way to build applications.
=> Add link to GitHub action

.github/workflows/android.yml
As discussed with @AndreMiras  in #1212 it's better to target `p4a.branch = develop` during automated tests.
=> Use develop branch for automated tests

buildozer/default.spec, buildozer/targets/android.py
**Needs https://github.com/kivy/python-for-android/pull/2301 to be merged.**
This PR adds the support for `manifestPlaceholders` feature that's it's now implemented in `python-for-android`
=> Add manifestPlaceholders feature

buildozer/default.spec, buildozer/targets/android.py
Now, if a buildozer is in a Docker container, to make it work with a Linux host you [have to pass several unobvious flags to the Docker](https://github.com/tshirtman/Buildozer-docker#installing). I wasn't able to make it work with Windows host at all.
However, it's possible to achieve the same much easier, if we could [pass a flag to the adb command](https://stackoverflow.com/a/53765498/1113207). It makes buildozer in a Docker work without any additional Docker flags and on any host (AFAIK).
The PR adds a possibility to pass an argument(s) to the adb. Uncomment the default value (`-H host.docker.internal`) and run `buildozer android deploy` from inside Docker to see the effect.
=> Add android.adb_args option

buildozer/__init__.py, buildozer/default.spec, buildozer/targets/android.py
=> Allow displaying only the logcat of our app.

.deepsource.toml, buildozer/__init__.py, buildozer/targets/android.py, buildozer/targets/osx.py
Hi 👋 I ran the [DeepSource](https://deepsource.io/) static analyzer on the forked copy of this repo and found some [interesting code quality issues](https://deepsource.io/gh/ankitdobhal/buildozer/issues/). This PR fixes a few of them.
- Added .deepsource.toml to fix bug risks
- Remove unnecessary use of comprehension
- Use `os.environ.copy()` to copy the environment variables
- Remove unnecessary return statement
- Use `sys.exit()` calls
- [✔] Antipattern
- [✔] My code follows the style guidelines of this project
=> chore : Fixed code quality issues

buildozer/default.spec, buildozer/targets/android.py, tests/targets/test_android.py, tests/targets/utils.py
Currently it's not possible to set own p4a mirror (not a fork on GitHub) in buildozer.spec.
This possibility already exists for kivy_ios, but not for p4a.
This PR allows to setting custom URL for p4a in the spec, instead of simply specifying fork.
The URL is used at first place. If no URL is specified, then fallback to github fork happens:
* p4a.url is set => URL is used;
* no p4a.url is set => https://github.com/{p4a.fork}/python-for-android.git is used;
* no p4a.url and no p4a.fork is set => default upstream (https://github.com/kivy/python-for-android.git) is used.
Backward compatibility with old specs is preserved with no behavioral changes.
=> Allow setting custom p4a URL instead of fork

buildozer/default.spec, buildozer/targets/ios.py, tests/targets/test_ios.py
During testing of iOS codesign a few issues were found:
- missing ability to specify development team, which is required;
- missing allowProvisioningUpdates option;
- exportFormat option was still used, despite the fact that it was removed in Xcode 8.3.
This PR addresses these issues.
As a result, I was able to get properly signed IPA:
```
Exported testapp to: /Users/jenkins/Jenkins/workspace/testapp/ios-debug/.buildozer/ios/platform/kivy-ios/testapp-0.1.7.intermediates/testapp-0.1.7.ipa
** EXPORT SUCCEEDED **
```
=> Update iOS codesign options

buildozer/default.spec, buildozer/targets/android.py
Complement to https://github.com/kivy/python-for-android/pull/2385 now merged into p4a develop.
=> Add enable_androidx

buildozer/default.spec, buildozer/targets/ios.py
This PR enables `manifest.plist` iOS generation, which can be used for installing the IPA via Safari.
=> iOS OTA manifest generation for in-house app distribution

buildozer/targets/android.py
I tried using ndk `22` and got an `AttributeError: 'NoneType' object has no attribute 'group'`.
This should also fix the download link logic (b/c '9' > '10' and '10e' also has a .bin extension according to the linked gist).
Fixes  #1029
Closes  #1130 (missed that one :sweat_smile: -- this seems like a better fix to me)
=> fix ndk version check & download link

buildozer/default.spec, buildozer/targets/android.py
see related p4a PR: https://github.com/kivy/python-for-android/pull/2446
This exposes the p4a options added in the referenced PR in `buildozer.spec`.
=> android: adaptive icon/launcher: expose p4a options in buildozer.spec

buildozer/targets/ios.py
Support for the old API was removed in Python 3.9 by bigfootjon.
This new API has been available since 3.4.
Issue: https://bugs.python.org/issue36409
=> Fixes deprecated plistlib API

buildozer/target.py, buildozer/targets/android.py, tests/test_buildozer.py
There are small typos in:
- buildozer/target.py
- buildozer/targets/android.py
- tests/test_buildozer.py
Fixes:
- Should read `specified` rather than `speficied`.
- Should read `overridden` rather than `overriden`.
- Should read `instantiated` rather than `instanciated`.
Closes #1326
=> docs: fix a few simple typos

buildozer/default.spec, buildozer/targets/android.py
This PR adds a configuration option `p4a.commit` that can be used to require the same exact python-for-android revision for every build.  (edit: rebased to remove spurious commits)
=> Let buildozer.spec files pin to a specific p4a commit hash

docs/source/installation.rst
Instructions for installing Buildozer on Windows 10
=> Update instalation.rst for Windows 10

buildozer/targets/android.py
This change makes log_level=2 show output for debugging recipes, when building them.
=> Pass debug loglevel down through to python for android

buildozer/default.spec, buildozer/targets/android.py
1) Add `android.add_assets` command, a front end for p4a's existing `--add-asset` command.
Required for newer Android Tensorflow Lite Java modules that require the `.tflite` file to be in the assets directory. 
2) Add a comment to #source.exclude_patterns to clarify a common user issue.
=> Add android.add_assets

buildozer/targets/ios.py
Without destination being set, archive command fails on a M1 Mac:
```
Command line invocation:
/Applications/Xcode.app/Contents/Developer/usr/bin/xcodebuild -alltargets -configuration Debug -scheme app -archivePath .../.buildozer/ios/platform/kivy-ios/app-0.0.1.intermediates/app-0.0.1.xcarchive archive ENABLE_BITCODE=NO DEVELOPMENT_TEAM=...
User defaults from command line:
IDEArchivePathOverride = .../.buildozer/ios/platform/kivy-ios/app-0.0.1.intermediates/app-0.0.1.xcarchive
IDEPackageSupportUseBuiltinSCM = YES
Build settings from command line:
DEVELOPMENT_TEAM = ...
ENABLE_BITCODE = NO
--- xcodebuild: WARNING: Using the first of multiple matching destinations:
{ platform:macOS, arch:arm64, variant:Designed for [iPad,iPhone], id:... }
{ platform:iOS, …
```
=> iOS: force archive iOS destination

.ci/osx_ci.sh, .github/workflows/ios.yml, buildozer/targets/ios.py, tests/targets/test_ios.py
This PR improves CI workflow and adds our Apple Silicon M1 runner in matrix, so we can test changes also on Apple Silicon.
Unfortunately, unless we configure a keychain with Provisioning and Development profiles, we're unable to discover issues like the one that has been fixed via #1392
=> Improves iOS CI workflow and adds Apple Silicon M1 runner

.github/workflows/android.yml, buildozer/default.spec, buildozer/target.py, buildozer/targets/android.py, docs/source/quickstart.rst, tests/targets/test_android.py
This PR adds aab (Android App Bundle) support to `buildozer`.
Shouldn't be merged until https://github.com/kivy/python-for-android/pull/2467 is ready and merged into the p4a `develop` branch.
TODO:
=> Add aab (Android App Bundle) support

buildozer/targets/android.py
The arch is no longer used in the download url for NDK23+
=> Changes for NDK23

.github/workflows/ios.yml
- Same of https://github.com/kivy/kivy/pull/7885
- https://github.com/actions/runner/releases/tag/v2.292.0 now supports Apple Silicon natively. 🥳
- The run_wrapper that was enforcing arm64 on top of a x86_64 process is now un-needed.
- There's a pending PR in actions/python-versions which is expected to introduce support for universal2 versions of Python, so hopefully, we will be able to rely on actions/setup-python also for our self hosted runner in a while..
=> Our self-hosted Apple Silicon runner now has been migrated to actions/runner v2.292.0 which now supports arm64 natively

buildozer/targets/android.py
Currently, android.add_src does not work anymore.
Using --add-source from p4a make it work again.
=> use p4a --add-source instead of manual copy of java files

buildozer/default.spec
Similar to #1041 
Note that this is only the template spec file and `DEFAULT_ANDROID_NDK_VERSION` fallback is left untouched.
=> Updates default buildozer.spec NDK from 19b to 23b

CHANGELOG.md, buildozer/__init__.py
Release time 🥳
Since a new `python-for-android` release that supports is expected to land soon (https://github.com/kivy/python-for-android/pull/2638), and Google changed the naming of the NDK packages since version 23, a new `buildozer` release that contains the fix (https://github.com/kivy/buildozer/pull/1427 and https://github.com/kivy/buildozer/pull/1462) is also needed.
=> Update CHANGELOG and prepare release 1.4.0

.github/workflows/android.yml
As `python-for-android` CI ([see](https://github.com/kivy/python-for-android/blob/b3e8c0378d65bd7f705b90fc915c4068b34d1b9a/.github/workflows/push.yml#L9)) , also the CI runs for Android in `buildozer` need to have `PYTHONFORANDROID_PREREQUISITES_INSTALL_INTERACTIVE` set to `0`.
This is needed as `python-for-android` now handles a prerequisites check + advice + install (on macOS, coming soon to other platforms), and expects input from the user.
⚠️ Working on docs, and that option will be included also on `buildozer` docs.
=> p4a prerequisites install should be done in non-interactive mode during CI builds.

buildozer/default.spec, buildozer/targets/android.py
Depends on https://github.com/kivy/python-for-android/pull/2330
=> Add support for p4a option --res_xml

buildozer/__init__.py, buildozer/target.py, buildozer/targets/android.py, buildozer/targets/ios.py, tests/targets/test_android.py, tests/targets/test_ios.py
See full story here:
https://github.com/kivy/buildozer/issues/1433#issuecomment-1112906681
https://github.com/kivy/buildozer/issues/1433#issuecomment-1113074469
https://github.com/kivy/buildozer/issues/1433#issuecomment-1113958798
=> Avoid the usage of `shell=True` in Popen, which could lead to potential security risks.

tests/targets/test_android.py, tests/test_buildozer.py
- We dropped `Python2` support here: https://github.com/kivy/buildozer/pull/1094
- `six` dependency was still required by tests, but not installed.
- Seems that GitHub removed `six` from the pre-installed Python packages in version `20220724` of the Ubuntu 20.04 virtual-environment, so the test started to fail just recently.
=> Removes `six` dependency in tests

buildozer/__init__.py
- Assert is a keyword and a space is needed + the parentheses are not needed.
- A recent change in pycodestyle (See: https://github.com/PyCQA/pycodestyle/pull/1063) introduced this check.
- CI runs started to fail this evening.
=> Fixes some E275 - assert is a keyword.

buildozer/targets/android.py
Buildozer wont build if a presplash color is set, this should fix it as described in #1487
=> Fix presplash color

buildozer/targets/android.py
Targets issue #1493 
`python-for-android` may require input from the user (e.g. when a prerequisite is not met and should be installed)
💡 We may want to introduce an API that checks if a feature is available, to avoid mimicking a real call that requires that feature.
=> Show output during aab support check, as p4a may require the user input

buildozer/targets/android.py
1. Initial FreeBSD support using Linux binaries.
* FreeBSD can emulate Linux ELF binaries [1].
* Use the same process for FreeBSD as for Linux.
* Add FreeBSD recognition in checks.
[1] https://docs.freebsd.org/en/articles/linux-emulation/
2. Fix 64-bit detection based on os.uname.
* Not every OS uses `x86_64` in `uname` (i.e. FreeBSD uses `amd64`).
* Every 64-bit OS will have 64 in `uname`.
* Alternatively `platform.architecture()[0]` will return `64bit`.
=> CeDeROM add FreeBSD support 20221014.

buildozer/default.spec, buildozer/targets/android.py
Related to: https://github.com/kivy/python-for-android/pull/2693
>- **As of Python 3.5, the `.pyo` filename extension is no longer used and has been removed in favour of extension `.pyc`**
All the references to `pyo` has been removed. `--no-compile-pyo` build option has been removed in favor of `--no-byte-compile-python`, which doesn't refer to a specific filename extension.
=> Removed (broken) `--no-byte-compile-pyo` support and added support for `--no-byte-compile-python`

tox.ini
See:
- https://github.com/PyCQA/flake8/issues/1760
From https://flake8.pycqa.org/en/latest/user/configuration.html :
> Following the recommended settings for [Python’s configparser](https://docs.python.org/3/library/configparser.html#customizing-parser-behaviour), Flake8 does not support inline comments for any of the keys. So while this is fine:
```
[flake8]
per-file-ignores =
__init__.py: F401
```
> this is not:
```
[flake8]
per-file-ignores =
__init__.py: F401 # imported but unused
```
Same of https://github.com/kivy/python-for-android/pull/2708
I also took the occasion to do some cleanup.
=> Flake8 does not support inline comments for any of the keys. + Cleanup some ignored errors/warnings

buildozer/__init__.py, buildozer/default.spec, buildozer/targets/android.py, docs/source/specifications.rst, tests/targets/test_android.py
Related `python-for-android` PR: https://github.com/kivy/python-for-android/pull/2739
- `orientation` option is now (as it should be) cross-platform, and does not accepts values which are only available on Android `screenOrientation` setting.
- `android.manifest.orientation` offers an additional layer of control for users that need to set a specific `screenOrientation` into the `AndroidManifest.xml` file.
=> Makes orientation option cross-platform and conform to latest python-for-android changes, adds `android.manifest.orientation`.

buildozer/default.spec, buildozer/targets/android.py, tests/targets/test_android.py
Related python-for-android PR: https://github.com/kivy/python-for-android/pull/2725
`android.permissions` now accepts all the syntaxes supported by `python-for-android`.
Removed broken and un-needed checks related to android permissions:
- `_get_available_permissions ` is looking for a file that does not exist anymore at the provided location, so everything is already considered "ok". Basically the check is already skipped.
- Forcing the last component to be uppercase can lead to multiple issues.
In general, IMHO is better to leave the error-handling for Android-specific things to the Android toolchain (or to `python-for-android` if it makes sense), as these things change fast .
=> Removes broken and unneeded checks, now we can support additional permission syntaxes.

buildozer/targets/android.py
Corrections for:
- extra-manifest-xml
- extra-nanifest-application-attributes
following issues detected:
android.features = android.hardware.sensor.accelerometer
results in:
toolchain.py: error: unrecognized arguments: --feature android.hardware.sensor.accelerometer
as a workaround I tried to supply a file containing the xml like:
android.extra_manifest_xml = ./xml/feature.xml
then toolchain parameter generated bei buildozer is wrong.
`... , '--extra-manifest-xml="<uses-feature\n      android:name="android.hardware.sensor.accelerometer"\n        android:required="true" />\n"', ...
`
p4a adds all contents after the equal sign to AndroidManifest, i.e including these additional double quotes - this is not correct.
After my change this works correctly. It produces the toolchainparameter (in 2 …
=> Corrections (fixes) for extra-manifest-xml

Dockerfile, docs/source/installation.rst
As a user has reported here: https://github.com/kivy/buildozer/issues/1565 (and on Discord), `Cython==0.29.19` is not working anymore with the `develop` branch of `python-for-android`.
This PR updates the suggested version in docs.
=> Update the suggested `Cython` version in docs to `0.29.33`

docs/source/installation.rst
`python-for-android` is now taking care of prerequisites check on macOS (and install, if the user is fine with it), and the provided instructions are incomplete/outdated.
=> Docs: Android on macOS - Remove outdated instructions

buildozer/default.spec, buildozer/targets/android.py
`python-for-android` does not support `public` storage anymore (since a while), and therefore does not support `--dir` flag.
Ref: https://github.com/kivy/python-for-android/issues/363
Fixes issue #1591
=> `python-for-android` does not support `--dir` flag anymore.

buildozer/default.spec, tests/targets/test_ios.py
Latest Xcode removes support for older simulators and complains while trying to link
```
ld: file not found: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/arc/libarclite_macosx.a
```
Using latest branch from ios_deploy seems to fix the issue.
=> Update ios_deploy branch to 1.12.2 Needed for latest Xcode.

buildozer/__init__.py
checkbin used custom code to find where a binary is on the path. 
shutil.which is a built-in to do the same thing since Python 3.3. 
Simpler and works across platforms.
=> Refactor checkbin to use shutil.which

.github/workflows/test_python.yml
This test was only meant to make sure that we show the "not compatible with python2" error.
More testing is generally great, but unfortunately `python2` is not available anymore via `setup-python` and the pipeline is now failing.
If we want to keep the test up and running, we need to do that in another way, but it will increase the complexity of our CI.
=> Remove `python2` test as `python2` is not available anymore via `actions/setup-python`

buildozer/__init__.py, buildozer/logger.py, buildozer/scripts/client.py, buildozer/scripts/remote.py, buildozer/target.py, buildozer/targets/android.py, buildozer/targets/ios.py, buildozer/targets/osx.py, tests/targets/test_ios.py, tests/targets/utils.py, tests/test_buildozer.py, tests/test_logger.py
First step toward #1629.
Code related to logging moved into its own class/file.
References (including in targets and tests) updated.
Unit tests separated out, and enhanced to test more conditions.
Trivial indenting/grammar issues in osx.py fixed.
No-op exception handling code removed.
=> Factor out logging code from Buildozer class

.github/workflows/android.yml, .github/workflows/ios.yml, Dockerfile
`Cython>=3.0.0` broke our CI pipeline.
But it's not `Cython` fault, instead, we urge to change our `python-for-android` and `kivy-ios` logic to not rely on a single specific `Cython` version for all the packages, as every package should be able to decide the `Cython` (and other build-time-only packages to use).
Meanwhile, to keep the development up and running, that seems the faster solution.
=> Use a pinned version of `Cython` for now, as most of the recipes are incompatible with `Cython==3.x.x`

.github/workflows/test_python.yml, docs/source/installation.rst, setup.py
Stop testing on Python 3.7 (end of life)
Explain more clearly in documentation what versions are supported. 
Update list of classifiers.
=> Update Python version support

buildozer/__init__.py, buildozer/default.spec, buildozer/scripts/remote.py, buildozer/specparser.py, buildozer/targets/android.py, tests/test_specparser.py
Separate ConfigParser code from Buildozer.
- Use subclass, rather than monkey-patching.
- Single implementation of list-handling code.
- Convenience functions to minimise impact of existing code (but instantly deprecated).
- Treat defaults consistently
- Apply the env overrides automatically (client doesn't need to trigger).
- Apply the env overrides once (read-time) rather than on every get.
- Avoid re-using term "raw" which has pre-existing definition in ConfigSpec.
- Update android.py client to match,
- Unit tests.
Add comments to start and end of default.spec to explain the syntax (as discussed in #1636)
=> Separate ConfigSpec parser (Address #1636)

buildozer/default.spec
Also trivial copy-edits to other comments.
=> Document service options in default.spec

buildozer/targets/android.py
There is no win32 support for the Android target. This doesn't change that. It does, however, enable experimental support, via an (unpublished) environment variable, to allow exploration of what is required.
Also, there are some signs of vestigial attempts at supporting Windows. As they haven't been run before, they need a little care:
- Updated references from _winreg to winreg (Built-in module was renamed in Python 3.)
- Corrected download URL to Android NDK for the Windows platform
- Supported sdkmanager installer having a different name (.bat extension) on Windows.
- Also corrected trivial formatting error in Exception text, which applies to all platforms.
=> Minor Win32 improvements

buildozer/buildops.py, buildozer/exceptions.py, tests/test_buildops.py
I am planning a moderately large refactor (not game-changing, but bigger than a typical PR) so have divided this change into several steps, purely to make reviewing easier and to increase confidence in the changes.
----
The Buildozer class includes a number of very basic OS-level methods required for building, but which require no knowledge about what is being built.
In particular:
* `checkbin()`
* `cmd()`
* `cmd_expect()`
* `mkdir()`
* `rmdir()`
* `file_matches()`
* `file_exists()`
* `file_rename()`
* `file_copy()`
* `file_extract()`
* `file_copytree()`
* `download()`
The Buildozer class is too big and has too many responsibilities, so I want to move all of these into a separate file, `buildops.py`, and update the clients.
However, *this* PR is *just* creating the new file, ready to be …
=> Introduce buildops

buildozer/__init__.py, buildozer/scripts/client.py, buildozer/scripts/remote.py, buildozer/targets/android.py, buildozer/targets/ios.py, tests/scripts/test_client.py, tests/targets/test_ios.py
This is a refactor; it adds no new functionality, but is part of a larger effort to move code out of (too large) `buildozer/__init__.py`.
Also made any import lists that were touched pep8-compliant in sort order.
=> Move Exception declarations into own file

buildozer/__init__.py, buildozer/target.py, buildozer/targets/ios.py
This is a refactor as one step to reduce the size/complexity of the Buildozer class. It doesn't change functionality. except to improve logging consistency and a small performance improvement
* mkdir() and rmdir() methods removed from `buildozer/__init__.py` (cleaner versions are already in `buildops.py`)
* All references to buildozer's mkdir and rmdir changed over to use buildops.
* Call to Linux's mkdir via a separate shell replaced with (faster, and platform independent) library call.
* Re-ordered imports, where touched, to match PEP8.
=> Migrate all usages of mkdir and rmdir to buildops

buildozer/__init__.py, buildozer/target.py, buildozer/targets/android.py, buildozer/targets/ios.py, buildozer/targets/osx.py, tests/targets/test_android.py
This is part of a bigger refactor to reduce the size and complexity of the Buildozer class. It adds no new functionality (apart from making logging more consistent)
* Remove file_rename, file_copy and file_copytree from Buildozer.
* Update all references to those Buildozer methods to refer to buildops equivalents.
* Note: `file_rename` is now called rename as, in practice, it was also used to rename directories.
* Updated all references to shutil.copyfile and shutil.rmtree to use the Buildops equivalents
* Note this adds implicit debug logging, making them more consistent.
* Updated all references to check_call() and check_output() that called the `rm` and `cp` shell commands.
* Note this adds implicit debug logging, making them more consistent, and improves performance.
* Updated mock in …
=> Migrate to use Buildop's rmtree, file_copy, file_copytree and rename

buildozer/__init__.py, buildozer/target.py, buildozer/targets/android.py, buildozer/targets/ios.py, tests/targets/test_android.py, tests/targets/test_ios.py, tests/targets/utils.py, tests/test_buildozer.py
This is part of a larger refactor, to reduce the size and complexity of the Buildozer class.
* Remove `file_matches()` method from the Buildozer class.
* Change the singular reference to it in `android.py` to use the buildops function.
* This raises the question: Will this be useful to other targets in the future, or should this be moved into the android target? Left for future refactors.
* Remove the `file_exists()` method from the Buildozer class.
* Change all the references to use the buildops function.
* Note for consistency with the other buildop functions, buildops.file_exists() takes a single parameter rather than `*args` and doesn't join the path together. One client call needed to be changed to accommodate that.
* Note that in several places, the code checks for the existence of …
=> Use buildops for file_exists and file_matches

buildozer/targets/ios.py
CC: @Julian-O 
We both did not see that the method name was wrong, since we likely were too much focused on `self.buildozer` --> `buildops`.
This only means that we need to improve our tests.
=> Fix a typo introduced during PR #1669

buildozer/__init__.py, buildozer/targets/android.py, buildozer/targets/ios.py, buildozer/targets/osx.py, tests/targets/test_android.py, tests/targets/test_ios.py, tests/targets/utils.py, tests/test_buildozer.py
This is part of a larger refactoring to simplify the Buildozer class.
* Remove checkbin() and download() methods (plus some definitions only used by download().
* Migrates all references to use the Buildops equivalents.
* Migrate shelling out to "curl"  to use download instead.
Note: The Buildops versions have completely different implementations to the original Buildozer ones, but the semantics are the same. New versions are more platform-independent, expected to be faster and don't use deprecated  library calls.
[Note to reviewers: This should be a straightforward one, but heads up that I am expecting the *next* PR to be a doozy.
=> Move checkbin and download to use buildops.

.github/workflows/test_python.yml
The RST files in a pull request might be malformed. URLs might be broken. These should be included in the unit-tests so they are immediately noticed.
This runs a Sphinx build on the documentation (and throws away the result). It also runs a URL check.
Note: The existing documents have some warnings - look for a separate PR to address those.
I did experiment, and confirm that an error like a bad URL causes this test to fail.
=> Add tests of the documentation.

docs/source/specifications.rst
The section in the documentation on source.includes/excludes is:
* Incomplete. It doesn't mention `include_patterns` or "hidden" files.
* Wrong: It says "If [`source.exclude_exts` is] 
empty, no files will be excluded based on their extensions." Reading the code reveals that if `source.exclude_exts` is empty, it has no effect.
* Unclear: Little mention on how the different options interact.
This is a re-write to attempt to fix that.
=> Rewrite section in documentation about on source include/excludes

docs/source/conf.py
There is an internal link to 'specifications' that requires a Sphinx extension to be installed to work.
There are no  custom static files, so removed spurious mention to `_static` directory,
=> Correct documentation configuration

buildozer/__init__.py, buildozer/buildops.py, buildozer/target.py, buildozer/targets/android.py, buildozer/targets/ios.py, buildozer/targets/osx.py, tests/targets/test_android.py, tests/targets/test_ios.py, tests/targets/utils.py, tests/test_buildops.py, tests/test_buildozer.py
[Attempt No. 2]
This is part of a bigger refactor to reduce the size and complexity of the Buildozer class (and bring it closer to cross-platform).
* Remove buildozer's cmd, cmd_expect and file_extract functions, and tests.
* Migrate clients to use buildops.cmd()
* Note that the implementation is completely different.
* Particularly, it doesn't depend on fcntl, so it runs cross-platform.
* It is much more explicit about the parameters it accepts.
* It no longer accepts `sensible` param; `quiet` has the same effect.
* It returns a named tuple, rather than a tuple; took advantage of replacing "magic number" indices with meaningful names.
* The treatment of environment variables has changed.
* Old system:
* buildozer.environ contained a list of deltas - overrides to the os.environ variables. …
=> Migrate to use cmd, cmd_expect and file_extract from Buildops.

.github/workflows/android.yml, .github/workflows/ios.yml, .github/workflows/pypi-release.yml, .github/workflows/support.yml, .github/workflows/test_python.yml
In the various YAML files, the Github actions are locked to particular versions.
Some actions are out of date and are causing deprecation annotations. e.g.:
> **pypi_release**
The following actions uses node12 which is deprecated and will be forced to run on node16: actions/checkout@v2, actions/setup-python@v2. For more info: https://github.blog/changelog/2023-06-13-github-actions-all-actions-will-run-on-node16-instead-of-node12-by-default/
This PR updates all of the actions to the latest.
I briefly looked for any changes that affected this CI, but I didn't find any, which was as expected.
=> Update github actions to latest versions

buildozer/target.py, buildozer/targets/android.py, buildozer/targets/osx.py
1) Target class contained Android-only attribute "artifact_format". Moved that code into TargetAndroid class.
2) TargetIos had a `check_build_prepared()` method that was ineffective.
`prepare_for_build()` sets `target._build_prepared` to True. Then `check_build_prepared()` inexplicably set it to False. Then `build()` checks for its existence, rather than its value [this is code smell that is on my list for later], so the fact that it had been changed made no difference.
So, I removed the method, and the call to it.
2) TargetOSX had lots of methods that were identical to its base class implementations (three more, once the above steps were done). They don't need to be specified; they are inherited. I removed them. `osx.py` is now 20% smaller.
=> Clean up inheritance of targets

buildozer/__init__.py
* The mechanism used to determine if it was currently running in a venv was non-standard. Used technique recommended by [venv documentation](https://docs.python.org/3/library/venv.html#how-venvs-work).
* Rather than call a subprocess to run venv, use the built-in venv library.
* Rather than check if an attribute exists, define it in `__init__()` and see if it has changed.
* `self.venv` contained a directory path, but the folder name didn't need to be stored after the method returned. A Boolean was all that was required.
Also, some trivial clean ups thrown in:
* Comment improvements.
* Copy command didn't need to be logged; buildops will do that.
* Directory's existence doesn't need to be checked; buildops will do that.
=> Improve Buildozer's venv handling.

.github/workflows/android.yml
`buildozer` is already tested against all the supported Python versions.
During Android builds there's no need to stick on a specific Python version.
=> Use suggested (latest) Python3 version to perform Android builds

buildozer/__init__.py, buildozer/targets/android.py
Attributes of a class instance should, where possible, be defined in the `__init__()` method, for clarity (especially about lifetimes). Pylint has a [warning about this](https://pylint.readthedocs.io/en/latest/user_guide/messages/warning/attribute-defined-outside-init.html), but I can't see one from Flake8.
TargetAndroid has an attribute `_serials` which is defined  (*sometimes*) outside of `__init()__`, and its value is checked with `hasattr()`. Changed it to act like a normal instance attribute, defined in `__init__()`.
Buildozer() goes even further. It monkey-patches two attributes, `_build_prepared` and `_build_done` onto its associated target. These attributes have the same lifetime as the Buildozer instance. I removed the monkey-patching, and made them normal instance attributes of …
=> Remove some attributes defined outside of __init__()

buildozer/buildops.py, tests/test_buildops.py
Turns out Linux and the `zipfile` package don't get along, while Windows and `unzip` don't get along.
Provide both implementations, so it always works.
[This doesn't meet my stated goal of making all Windows-specific improvements also include making the code cleaner for other developers too. Sorry.]
=> Add alternate unzip implementation

README.md
=> Support Email Address Fixed in the Readme.md

.github/workflows/no-response.yml
1) The No Response action is running every 5 minutes, wasting CPU. Once a day is plenty.
2) If you fork the repository in order to contribute, and you want the CI test actions to run on each commit, you can inherit the original actions from the main repo. However, that also inherits No Response action, which can't run without an issue tracker. As a result, you receive a spurious error email every time No Response runs. While it is possible to individually exclude actions with some sort of regular expression parameter in the GitHub web-site, it is neater to have the action automatically skip if it isn't in the Kivy/* domain.
=> Stop No Response action running when unneeded.

buildozer/targets/osx.py
OSX Target was incorrectly using buildozer.buildops
=> Fix Osx Target to properly use buildozer.buildops

Dockerfile, README.md
Add macOS build instructions (requires different build type on Apple Silicon because it needs x86-amd64 emulation)
Upgrade Ubuntu to latest LTS
Upgrade JDK to required JDK 17, builds did not work with old JDK
=> Add macOS build instructions, upgrades

buildozer/targets/android.py, setup.py
=> Use `parse` from `packaging.version` instead of `distutils` `LooseVersion`

buildozer/targets/android.py
Oops, I've made a typo.
Unfortunately, CI/CD did not catch it as we're experiencing another issue which happens before this one gets triggered.
=> Fix typo on `packaging.version` import statement

buildozer/targets/osx.py
CI/CD pipeline started complaining about `E226 missing whitespace around arithmetic operator`.
This is a quick fix that fixes the issue.
=> Fix `E226` missing whitespace around arithmetic operator PEP8 failure

.github/workflows/android.yml
`python-for-android` now requires Java 17 to be available and selected during build, as gradle requires it.
The CI is currently failing due to that.
=> Ensure Java 17 is selected and available during build

FAQ.md, docs/source/installation.rst, docs/source/recipes.rst
Reported by the CI sphinx-build linkcheck command:
```
(recipes: line 28) broken https://python-for-android.readthedocs.io/en/latest/recipes/
(installation: line 119) broken https://python-for-android.readthedocs.io/en/latest/troubleshooting/
```
=> :memo: Fix broken documentation links

.github/workflows/test_python.yml
Handle aggregated Coveralls reports using the `COVERALLS_PARALLEL` environment variable and the `--finish` flag. This prevents duplicate report submissions in the workflow matrix, which sometimes led to 422 "Unprocessable Entity" errors during upload:
```
Error running coveralls: Could not submit coverage: 422 Client Error:
Unprocessable Entity for url: https://coveralls.io/api/v1/jobs
```
Also updated the service name to `github-actions`, as suggested in:
- https://github.com/lemurheavy/coveralls-public/issues/1607#issuecomment-1000935999
- https://coveralls-python.readthedocs.io/en/latest/usage/configuration.html#github-actions-support
=> :construction_worker: Fix Coveralls parallel reporting

.github/workflows/docker.yml, README.md
- multi-platform build using buildx
- push to DockerHub and update DockerHub README on push to master or tagging
- use the Docker Hub registry for caching image layers to speed up builds
=> :construction_worker: Publish to DockerHub

.github/workflows/docker.yml, README.md
Also publish to the GitHub Container Registry as a fallback method, fixes #1887
=> :construction_worker: Docker push to GHCR

buildozer/default.spec, buildozer/targets/android.py, docs/source/specifications.rst
This PR enables display-cutout for Android devices. It's just a hook for the merged [p4a-PR](https://github.com/kivy/python-for-android/pull/2969) in order to use this option with Buildozer.
Everything is documented.
=> Android support display cutout

buildozer/default.spec
Everything in the title :-) some users were confused by the absence of the option when they needed a multi-orientation app.
=> Re-add "all" to the list of valid orientations in default buildozer.spec
