buildozer/__init__.py
Fixes black text which cannot be seen in Linux.
=> fix black text in log

buildozer/libs/_structures.py, buildozer/libs/version.py, buildozer/targets/android.py
=> needs testing, should fix #201 using pypa implementation of PEP440

LICENSE
=> Updated Licence Year

buildozer/__init__.py, buildozer/targets/android.py, buildozer/targets/android_new.py, buildozer/targets/ios.py
=> fix usage exception

buildozer/targets/android_new.py
Store p4a revamp files in `.buildozer`. Requires kivy/python-for-android#720
=> use p4a revamp --storage-dir option

buildozer/targets/android.py
=> fix bad placement of expanduser()

buildozer/targets/android.py
Thanks to @mixedCase for pointing out the issue in #286.
=> fix incorrect api/minapi values

buildozer/targets/ios.py
Let kivy-ios handle the icons.
=> fix icons for ios target

buildozer/targets/android.py
=> fix changing android branch

buildozer/targets/ios.py
`xcrun PackageApplication` is deprecated on OSX 10.10+. Combined with another recent change, this results in an error and failure to build the package. This change removes the use of the deprecated function and replaces it with separate archive and export steps.
=> ios: refactor deprecated PackageApplication command

buildozer/targets/osx.py
Remove Keka and use dmg instead of 7z.
=> Use dmg instead of 7z

buildozer/target.py
Fixes https://github.com/kivy/buildozer/issues/593.
=> Imported os to fix ImportError

buildozer/default.spec
See https://github.com/kivy/buildozer/commit/11f9dfaa509cf11cc4e3376a9f75f14ea0ad12c9
=> Fixes `p4a.branch` comment

docs/source/installation.rst
Basically the same as Ubuntu 16.04
=> Updates installation.rst with Ubuntu 18.04 instructions

.github/ISSUE_TEMPLATE.md
See what it looks like on my fork:
https://github.com/AndreMiras/buildozer/issues/new
=> Adds issue template with basic required info

buildozer/targets/android_new.py
Untested
https://i.imgur.com/BfRhQTA.png
=> Quote --storage-dir value

buildozer/targets/android.py
Now deals with conditional statements introduced in:
https://github.com/kivy/python-for-android/pull/1418
=> Updates p4a deps parsing

buildozer/__init__.py
=> Fixes Invalid cross-device link

buildozer/targets/android.py
This resolved issues when both Python 2 and Python 3 were installed.
=> Explicitly run `pip3` when using Python 3

buildozer/__init__.py, buildozer/default.spec
=> support sensorLandscape mode. resolves #762

buildozer/targets/android.py
pythonforandroid/toolchain.py has been changed.
https://github.com/kivy/python-for-android/commit/d8e3d516eb4409d3b97fb2b0ed889343ba6d233a
=> Fix output directory for gradle

buildozer/targets/android.py, tests/test_buildozer.py, tox.ini
This test should fail due to #813. Next commit will fix it.
=> Unit tests buildozer --help command, refs #813

tests/test_buildozer.py
- adds test utils methods
- checks default log level
- sets log level via spec file
- checks messages printing depending on level
=> Unit test logger

README.md
Removed reference to Kivy VM as it doesn't actually exist
=> Removed reference to Kivy VM

.travis.yml, Dockerfile, buildozer/__init__.py, tox.ini
- installs cutting edge version from current source
- removes outdated java version fixes
- migrates to host Python3
- verifies the image builds and run via Travis
=> Various Dockerfile improvements

buildozer/__init__.py, buildozer/default.spec, tests/test_buildozer.py
Helps with troubleshooting and error reporting.
Also closes #824
=> Changes default log level to debug (2)

buildozer/__init__.py, tests/test_buildozer.py
Also fixes stderr/stdout writing refs #743.
=> Unit test unicode decode on command output, fixes #857

buildozer/targets/android.py
Linter regression introduced in #934, see:
https://github.com/kivy/buildozer/pull/934#discussion_r304309602
=> Minor linter fix

docs/source/installation.rst
- Python3 only, since this is now a p4a requirement
- links to p4a troubleshooting documentation
- fixes code block formatting on `Aidl` section
=> Updates install instructions and troubleshooting

.github/workflows/test_python.yml
Refs: https://github.com/kivy/buildozer/pull/1060#issuecomment-612168204
=> Coveralls TOKEN is only available on branch master

buildozer/targets/ios.py
=> Support for both input and raw_input in iOS target to avoid NameError with Python 3

.github/workflows/test_python.yml, setup.py, tox.ini
Makes sure the user is warned at install time if using Python 2.
=> Drops Python 2 support

CHANGELOG.md
To make the future release less painful and to follow the motto:
if it hurts do it more
Also documented in:
https://keepachangelog.com/en/1.0.0/
=> Updates CHANGELOG.md with unreleased section

docs/source/installation.rst
Refs: https://github.com/kivy/python-for-android/pull/2205
=> :books: Adds libssl-dev to the install dependencies

Dockerfile, docs/source/installation.rst
=> :arrow_up: Bumps Ubuntu and OpenJDK versions

.github/workflows/android.yml, .github/workflows/test_python.yml, README.md
This is in preparation for the soon to come ios build integration test.
=> :construction_worker: Moves Android build to dedicated workflow file

buildozer/__init__.py, buildozer/scripts/remote.py, buildozer/targets/android.py
Fixes https://github.com/kivy/buildozer/issues/971
=> Expand "~" before every path normalization.

docs/source/quickstart.rst
Added instructions to run an Android application from Windows 10
=> Update quickstart.rst for Windows 10

buildozer/default.spec, buildozer/targets/android.py
- See https://github.com/kivy/python-for-android/pull/2322
- refs https://github.com/kivy/python-for-android/issues/958
=> Add support for p4a --feature option

buildozer/targets/android.py
This PR fixes #1263 without reverting #1212
=> Change android.manifest_placeholders default to None

buildozer/__init__.py, buildozer/default.spec, buildozer/targets/android.py
A corresponding Pull Request in p4a is here: https://github.com/kivy/python-for-android/pull/2338
... and here: https://github.com/kivy/python-for-android/pull/2248
=> added few additional options for android p4a builds

buildozer/__init__.py
Next `buildozer` version will be `1.4.0`
=> Bump version to 1.4.0.dev0

buildozer/__init__.py
=> Bump version to 1.4.1.dev0

buildozer/__init__.py
=> Bump version to 1.5.1.dev0

buildozer/default.spec, buildozer/targets/android.py, docs/source/specifications.rst
The user can now set the application to be a home app (launcher).
=> Home app functionality

buildozer/default.spec, buildozer/targets/osx.py
`buildozer osx debug` should work now.
=> Update Buildozer osx target to work with latest kivy 2.2.0

tox.ini
=> Ignore W503 error

.github/workflows/support.yml
Make message a bit more empathetic, and give more directions about where to get help.
Also, add comment at top to help people who stumble on the YML file understand its role.
[Has not been tested.]
=> Modify automated "support" message.

buildozer/tools/packer/http/welcome/index.html
Fix for issue #748  , Documentation refers to buildozer.ini
=> Fixes typo in docs

README.md
Update tag for consistency with the instructions of the Dockerfile
=> Update Docker Build instructions in  README.md

Dockerfile
Use ubuntu:22.04 not ubuntu LTS, because the container is not ready for ubu 24.04 ;-)
=> Use `ubuntu:22.04` instead of `ubuntu:latest` in `Dockerfile`

buildozer/default.spec
=> Add Default options to buildozer.spec

buildozer/target.py, docs/source/quickstart.rst
Fix typos discovered by codespell
* https://pypi.org/project/codespell
=> Fix typos discovered by codespell

.github/workflows/test_python.yml
* https://github.com/actions/runner-images?tab=readme-ov-file#available-images `macos-latest` is macOS 15 ARM64
* https://github.com/actions/setup-python/releases
* https://github.com/actions/checkout/releases
* https://www.python.org/download/pre-releases
* https://www.python.org/downloads/release/python-3140rc2
=> Update Python workflow for version and action upgrades
